// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * SubmissionItem
 */
export type SubmissionItem = {
    /**
     * Id
     */
    id: string;
    /**
     * Formname
     */
    formName: string;
    /**
     * Data
     */
    data: {
        [key: string]: unknown;
    };
    /**
     * Schemahash
     */
    schemaHash: string;
    /**
     * Status
     */
    status: 'pending' | 'submitted' | 'failed';
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type GetErpSystemsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/erp-systems';
};

export type GetErpSystemsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type HealthCheckResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetItemByIdData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: number;
    };
    query?: {
        /**
         * Q
         */
        q?: string | null;
    };
    url: '/items/{item_id}';
};

export type GetItemByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetItemByIdError = GetItemByIdErrors[keyof GetItemByIdErrors];

export type GetItemByIdResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetDoctypeByNameData = {
    body?: never;
    path: {
        /**
         * Form Name
         */
        form_name: string;
    };
    query?: never;
    url: '/doctype/{form_name}';
};

export type GetDoctypeByNameErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDoctypeByNameError = GetDoctypeByNameErrors[keyof GetDoctypeByNameErrors];

export type GetDoctypeByNameResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetAllDoctypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/doctype';
};

export type GetAllDoctypesResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SubmitFormDataData = {
    body: SubmissionItem;
    path?: never;
    query?: never;
    url: '/submit';
};

export type SubmitFormDataErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SubmitFormDataError = SubmitFormDataErrors[keyof SubmitFormDataErrors];

export type SubmitFormDataResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
